### ISSUE TITLE
[gdae_dsd.py]   ValueError: When passing a list as loss, it should have one entry per model outputs

### ISSUE THREAD

**Issue by agangzz** [Js-Mim/mlsp2017_svsep_skipfilt#1]
After downloaded the DSD100 dataset,  I use the code "gdae_dsd.py" for training process, error is shown below:

ValueError: When passing a list as loss, it should have one entry per model outputs. The model has 3 outputs, but you passed loss=[<function KL at 0x7efcecd2b488>, <function KL at 0x7efcecd2b488>]

so I try to rivse the code like
model.compile(optimizer = opt, loss = [KL, KL, KL])
PS: orignal code is "model.compile(optimizer = opt, loss = [KL, KL])"

Another error happen:
ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 3 arrays but instead got the following list of 2 arrays: 

So, do you run into these issues? how to fix it?
Thanks

**Comment by Js-Mim** [comment]
Hey @agangzz ,

sorry for the late reply. I cannot reproduce the exact error you have attached,
but it is coming from line 100. If i am not mistaken, in the keras version i was using you could have an output without being attached to any gradient computation. And i was using the third output ("rnnDsv") for visualizing the outcome. You could simply remove it, and put back the two losses in model.compile.
