### ISSUE TITLE
Hello, I have a question about the batch_size of your project

### ISSUE THREAD

**Issue by 22w2w2** [Js-Mim/mlsp2017_svsep_skipfilt#4]
Hello, I feel your article is great, I currently use the compressed version of the DSD100 database, would like to test your code, but there is a mistake：
Can not feed value of shape (32, 18, 1025) for Tensor 'input_1: 0', which has shape '(1, 18, 1025)'
If I did not guessed it might be my batch_size is not the same as the batch_size of your trained model, how can I solve this problem? Do I have to use the standard DSD100 database for testing? Very much looking forward to your reply

**Comment by 22w2w2** [comment]
I'm very sorry, I still have a question in your IOmethods.py file, at line 108 your comment says to add windoows support but you have not added because I currently use the windows platform so I just need to As long as the 'ffmpeg_linux' and 'ffmpeg_osx' modified into windows on it? Because I now have an error can not read the data:
'All the reference sources should be non-silent (not all-zeros), but at least one of the reference sources is all 0s, which introduces ambiguity to the evaluation. (Otherwise we can add infinitely many all-zero sources.'
This bug comes from testGDAE.py's line 370

**Comment by Js-Mim** [comment]
Hi @22w2w2,

i think that you are setting a big batch size for the data you are trying to feed into the network.
Solution 1: While compiling the model try to set a smaller batch size.
Solution 2: During testing (e.g. model.predict(X)), set the batch size the same as the one you used while compiling the model.
Solution 3: Maybe you are giving a very small portion of the audio signal for processing (i.e. ~18 time-frames) which that would cause the reshaping function to yield a tensor which cannot be processed by the compiled model with a batch size of 32.

Hope that helps.
